# Generated by Django 5.2.4 on 2025-08-05 22:33

import apps.documents.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('ocr_enabled', models.BooleanField(default=True)),
                ('ai_extraction_enabled', models.BooleanField(default=True)),
                ('extraction_template', models.JSONField(blank=True, default=dict)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('required_fields', models.JSONField(blank=True, default=list)),
                ('max_file_size_mb', models.PositiveIntegerField(default=50)),
                ('allowed_extensions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'doc', 'docx'])])),
                ('file_size', models.PositiveIntegerField()),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('auto_detected_type', models.CharField(blank=True, max_length=100)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ocr_complete', 'OCR Complete'), ('extraction_complete', 'Extraction Complete'), ('review_required', 'Review Required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('error', 'Error')], default='uploaded', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('ocr_text', models.TextField(blank=True)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('ocr_language', models.CharField(blank=True, max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('contains_pii', models.BooleanField(default=False)),
                ('contains_phi', models.BooleanField(default=False)),
                ('data_classification', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted')], default='internal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.documenttype')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('auto_approve_threshold', models.FloatField(default=0.95)),
                ('status', models.CharField(choices=[('created', 'Created'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partially_completed', 'Partially Completed')], default='created', max_length=20)),
                ('total_documents', models.PositiveIntegerField(default=0)),
                ('processed_documents', models.PositiveIntegerField(default=0)),
                ('successful_documents', models.PositiveIntegerField(default=0)),
                ('failed_documents', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.documenttype')),
            ],
            options={
                'db_table': 'document_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentBatchItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('processing_order', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.documentbatch')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_items', to='documents.document')),
            ],
            options={
                'db_table': 'document_batch_items',
                'ordering': ['processing_order'],
                'unique_together': {('batch', 'document')},
            },
        ),
        migrations.CreateModel(
            name='DocumentExtraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.TextField()),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('currency', 'Currency'), ('email', 'Email'), ('phone', 'Phone'), ('address', 'Address')], default='text', max_length=20)),
                ('confidence', models.FloatField()),
                ('bounding_box', models.JSONField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('original_value', models.TextField()),
                ('corrected_value', models.TextField(blank=True)),
                ('correction_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='documents.document')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_extractions',
                'ordering': ['field_name'],
                'indexes': [models.Index(fields=['document', 'field_name'], name='document_ex_documen_f27d89_idx'), models.Index(fields=['is_verified'], name='document_ex_is_veri_ea3499_idx')],
                'unique_together': {('document', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='DocumentProcessingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.CharField(choices=[('upload', 'File Upload'), ('validation', 'File Validation'), ('classification', 'Document Classification'), ('ocr', 'OCR Processing'), ('extraction', 'Data Extraction'), ('validation_rules', 'Validation Rules'), ('review', 'Human Review'), ('approval', 'Final Approval'), ('error', 'Error Occurred')], max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='documents.document')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_processing_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', '-created_at'], name='document_pr_documen_0c80ff_idx'), models.Index(fields=['step', 'status'], name='document_pr_step_bbe01d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_by', '-created_at'], name='documents_uploade_918a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', '-created_at'], name='documents_status_e99d0b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type', '-created_at'], name='documents_documen_e45084_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_hash'], name='documents_file_ha_3bbf78_idx'),
        ),
    ]
